### ISSUE TITLE
ETO Flow fixes. Collective work. See checklist

### ISSUE THREAD

**Issue by SergejSoft** [Neufund/platform-frontend#1087]
- [x] Media  form returns 400 on adding new link. We have 250 caracters limit but if you put more. Form stop accepting this and the users still gets. 400

- [x] Changeheder text to: "ADD COMPANY YOUTUBE VIDEO LINK"
![youtube.png](https://images.zenhubusercontent.com/57dd639be40e5714b16f0753/21f0b759-ac3a-4f6c-8a9a-0e16515003d1)

- [ ] Term Sheet form user able to select eth or nEUR but not able to unselect. 
![eth select](https://user-images.githubusercontent.com/2290474/43132938-884b8810-8f3d-11e8-9fa6-2261f97c067d.png)

- [x] NEUMINEE SECTION TEXT: "TOKEN HOLDER REPRESENTATIVE''
In the drop down there should be only one value. Nominee.  (Pls. change in the imput form. Remove bulean as a requirement.)
![neuminee](https://user-images.githubusercontent.com/2290474/43133368-cf0156e4-8f3e-11e8-8082-1d8c933e55a8.png)

- [x] Youtube placeholder is missing.
- [ ] Legal form. Chart element for "How the funds will be spend" is missing 
https://zpl.io/VOkE1Qr

- [x]  All media links exccept YouTube mus be opening in the new tab. 

- [x] Key Individual form has Medial link section. Pls. add to the form. 
https://zpl.io/aMmY8nz
- [x] Update public view with social media icons/links. 
https://zpl.io/bAqgW8O

- [x] Progress calculation performance and correctness

- [x] Clicking cross(x) refreshes the page  (CHRIS)
![image](https://user-images.githubusercontent.com/1814312/43194024-b9d8c9fa-9001-11e8-8c20-9c0cef835d67.png)

**Comment by SergejSoft** [comment]
Are you gonna make a PR
