### ISSUE TITLE
Check Sentry Errors 

### ISSUE THREAD

**Issue by Moejoe90** [Neufund/platform-frontend#2107]
**Background** 
Sentry is giving back lots of reports, 
Some are unknown errors, others are known behaviors that shouldn't be logged 

**Task**
Clean up the sentry board by 

- [ ] 1 - Add Source maps to sentry
- [ ] 2 - Removing all known behavior error or false errors like logging someone canceling a withdraw operation etc 
- [x] 3 - Investigate some unknown errors into prospect tickets or correct bug reports that should be fixed

**Comment by AlexeyTuboltsev** [comment]
need to upgrade sentry first

**Comment by Desperado** [comment]
@AlexeyTuboltsev do we still need to update the sentry?

**Comment by Desperado** [comment]
First 10+ Sentry issues tackled, will be overviewed in the continuous basis
