### ISSUE TITLE
Test and Upgrade Redux-Saga

### ISSUE THREAD

**Issue by Moejoe90** [Neufund/platform-frontend#2118]
**Background**
We are in `pre-release` version 0.16.x 
the latest version is `1.0.1` There are some breaking changes but many great features and implementations that will help make the whole application tighter 
**Task**
- [ ] Upgrade to the latest version and make sure everything is running
- [ ] Remove from `neu*` wrappers (`neuCall`, etc) casting `saga as CallEffectFn<any>` as it should be no longer needed 
- [ ] Refactor our `neu*` wrappers (`neuCall`, etc) to spread `args` to the effect. (At the moment they are passed as `args[0], args[1], args[2], args[3], args[4]`.

**Comment by Moejoe90** [comment]
There is currently no clear API interface of documentation for changes things like 
`delay` are not there. 
It doesn't make sense to upgrade now until the stable version is released at some point

**Comment by desfero** [comment]
Ok let's push this as the stable version was already released more month ago

**Comment by Moejoe90** [comment]
Update there is already V1.1.3 
https://github.com/redux-saga/redux-saga/releases
Pushing to Christmass tech depth
