### ISSUE TITLE
nEUR Step 1 - Bank Verification 

### ISSUE THREAD

**Issue by falinebambi** [Neufund/platform-frontend#2409]
**Background**
nEUR Step 1 - Bank Verification 
On the platform, the user can use both ETH or nEUR. nEUR can be obtained through Quintessence PLC by linking the profile on the platform with the user's bank account.
The bank account gets linked by sending 1€ to the Quintessence account as verification (user gets 1nEUR during this action)

**PRD** https://docs.google.com/document/d/1tNrQGkVPDdSbSDaoJMNevPfQQtLjXc8l8Z_MZYA8MYo/edit

**Zeplin**
https://app.zeplin.io/project/5a8a92c89c1a166a6a6e8f37/dashboard?seid=5c585eeb4a2d813589e7c55e

**Acceptance criterea**
- [x] nEUR and ETH balance widgets should be split in the Wallet tab (please mind the new widget names)
- [x] Linked Bank Account widget should appear in Profile tab
- [x] for unverified user, nEUR balance widget should contain an information that no bank account is verified 
- [x] for unverified user, Linked Bank Account widget should contain a button that starts verification process
- [x] for unverified user, clicking PURCHASE, REDEEM and VERIFY BANK ACCOUNT buttons should start bank account verification process
- [x] user should be only available to continue the process when he accepts both terms of use 
- [x] user should receive an email with the transaction summary matching the data on the screen (iban, reference number etc) when the user's transfer was confirmed and his account credited with 1nEUR, nEUR
- [x] Linked Bank Account widget and nEUR balance widget should change after successful account verification

**Testing notes**
check if the correct bank account nr is shown in Linked Bank Account widget
check if link different account link goes to new verification process

**Comment by huesforalice** [comment]
To retrieve the current banking details of a user from the backend, there is an endpoint on the kyc api (you can check the swagger file). Right now it will only give you the last 4 digits of the account no we think you have. If we don't have anything on file, you will receive a 404. When my banking branch is merged, there will also be another field with the name of the account holder, which can be slightly different from what we have from the kyc. Please ask me directly if you have questions.

**Comment by rudolfix** [comment]
## technical notes
**when to enter this flow**
REDEEM button is inactive if user does not have `isVerified` flag set in identityRegistry OR it has `isFrozen` flag set
When (1) user is verified AND (2) user has bank account in API (status 200) AND (3) user has `hasBankAccount` flag in identityRegistry we go to redeem flow (#2334)

only when (1) user is verified AND (2) user does not have bank account in API (404) OR (3) user **does not have** `hasBankAccount` we go to Bank Verification

**the 1 EURO value**
is actually a setting in the `EuroTokenController` contract. please obtain current controller from `universe`
then take a look at
```
function minDepositAmountEurUlps()
        public
        constant
        returns (uint256)
    {
        return _minDepositAmountEurUlps;
    }
```
it's minimum deposit that can be accepted in the system. so **please replace 1 euro** everywhere with this value
please use this value to validate amount on #2335 purchase flow

**Comment by glupiawymowka** [comment]
only basic state verified atm, I still need to test states for verified account

- From the designs and ETH widget, I guess we should keep consistency and have non-active "Purchase" and "Redeem" buttons here 
![image](https://user-images.githubusercontent.com/18315589/53190138-35661980-3609-11e9-9d3a-06501ef8a775.png)

vs design
![image](https://user-images.githubusercontent.com/18315589/53190290-883fd100-3609-11e9-9c79-dfa3832f814d.png)


- The verification amount is unusually high if you compare it with other bank verification processes.
 Is it correct @rudolfix ? If yes, maybe we should explain it somewhere to the user?
*(note from Paweł was that Bank Details are to be added from backend)*

![image](https://user-images.githubusercontent.com/18315589/53190739-888c9c00-360a-11e9-8e8f-faed72a83e67.png)

**Comment by desfero** [comment]
Hey @glupiawymowka.

First one: After we set NEURO_WITHDRAW_ENABLED to 1 then you will see Purchase and Redeem but be aware that if you click Purchase and bank account is not verified we then start new verification process as it's in AC.
Second one: I get this from blockchain so it's not something hardcoded on frontend.

**Comment by glupiawymowka** [comment]
First one: It's fine, the comment was mostly about not having the empty space. I like it now :) 
Second one: we need to get information from @rudolfix. It's more a note to myself to not skip it.

**Comment by glupiawymowka** [comment]
@desfero @drakkein one thing that needs to be fixed: 
![image](https://user-images.githubusercontent.com/18315589/53347441-5e442280-3919-11e9-81ab-566e6e8e6fbe.png)

**Comment by glupiawymowka** [comment]
*tested on .net*
When user has a verified bank account, widget in unverified status shows up first after refresh. 

Steps to reproduce: 
1. log into an account with verified bank account
2. go to Wallet tab
3. refresh 
![verification refresh](https://user-images.githubusercontent.com/18315589/53401742-afebbc00-39b0-11e9-90fc-66b8ea8c58c0.gif)

**Comment by huesforalice** [comment]
Note from Backend: The endpoint for retrieving the bank account from the backend will change shortly. The new KYC API swagger definition will be like this: https://github.com/Neufund/platform-backend/pull/1388/files#diff-2218439222779daef8b2ae971df6c79b

**Comment by glupiawymowka** [comment]
changes discussed with @desfero and @rudolfix :
![image](https://user-images.githubusercontent.com/18315589/53416631-2fd74d80-39d4-11e9-9a0b-460ff39b6c6e.png)
1. AMOUNT => AMOUNT TO SEND
2. Below 1€, nEUR to receive: 1nEUR
3. There is a space missing before the last sentence (To avoid...)
