### ISSUE TITLE
nEUR Step 2 - Redeem flow

### ISSUE THREAD

**Issue by falinebambi** [Neufund/platform-frontend#2413]
**Background**
nEUR Step 2 - Redeem
The user can burn nEUR received from Quintessence or NEU payouts and receive 1:1 of EUR instead. To do so, he needs a verified bank account, where EUR will be sent. 

PRD https://docs.google.com/document/d/1tNrQGkVPDdSbSDaoJMNevPfQQtLjXc8l8Z_MZYA8MYo/edit

**Zeplin**

https://app.zeplin.io/project/5a8a92c89c1a166a6a6e8f37/dashboard?seid=5c58661a54201142002808ac 

**Component**

**Acceptance criteria**
- [x] action should be accessible by choosing REDEEM from nEUR balance widget (verified bank account)
- [x] all the nEUR owned by the user should be visible on the screen
- [x] important remark to the following screen (I can't edit in zepplin) - please be consistent. If the whole text is not in capitals, this is always **nEUR** and **EUR** (not neur, euros NEUR etc)
![image](https://user-images.githubusercontent.com/18315589/52416559-27cd7180-2aea-11e9-8854-aadff16b88d0.png)
- [x] user shouldn't be able to withdraw an amount lower than Bank Transaction Fee
- [x] user shouldn't be able to withdraw if total on his account is lower than Amount to redeem + fee
- [ ] when trying to withdraw more than Entire Wallet Balance, user should see error label "Sorry, the amount is above your wallet balance" 
- [ ] there should be consistency regarding estimated business days to complete the transaction (it's 4-6 for redeem)
- [ ] for an unsuccessful transaction, there should be a link to Support Desk
- [ ] TX Hash should be a link to transaction
- [ ] this is done when the correct amount of nEUR was deducted from user's account

**Testing notes**

**Comment by rudolfix** [comment]
## technical notes

1. redeem is only available when `isVerified` flag is set AND `isFrozen` flag is **not** set in identityRegistry
2.

**Comment by rudolfix** [comment]
Rounding info:
TOTAL REDEEMED: you round value from user input HALF UP to 5 decimal places (it's precision in SWIFT messages) then you apply the fee then you ROUND DOWN to two decimal places (this is Frick rounding)
BANK TRANSACTION FEE: you round value from user input HALF UP to 5 decimal places - TOTAL REDEEMED

**Comment by glupiawymowka** [comment]
Things to fix: 
1. Important: It should be Redeem Entire Wallet Balance (outdated design)
![image](https://user-images.githubusercontent.com/18315589/53504934-338dd180-3ab3-11e9-8ce5-7033c18191d8.png)

**COMMENTS TO THE FOLLOWING SCREEN**
![image](https://user-images.githubusercontent.com/18315589/53505059-6768f700-3ab3-11e9-8969-90fff3ca0a6c.png)

2. Bank name should go before bank account nr 
3. currencies should be: 9999 ETH; 999 nEUR, 999 EUR etc. .
4. Inconsistency in wording (it should be 4-6 business days as in the first window)

**Comment by glupiawymowka** [comment]
This might be a bigger task, but this is what happens if I cancel transaction signing in Metamask:
 
![image](https://user-images.githubusercontent.com/18315589/53505419-0db4fc80-3ab4-11e9-9bce-3decdbb54c3e.png)

design:
https://app.zeplin.io/project/5a8a92c89c1a166a6a6e8f37/screen/5c5865dd62086d356573d35d
