### ISSUE TITLE
ethereum transaction flow 

### ISSUE THREAD

**Issue by rudolfix** [Neufund/platform-frontend#2509]
**Background**

We are upgrading the all Ethereum transaction flows to include a summary of the transaction in the pending, rejected and successful states.

This summary will include in table format: Token name, Amount and Timestamp.

All pending transactions happening outside the platform will also be shown with less information in the summary (technical background in #1328) . Transaction statuses will now be viewable by clicking on the spinning icon in the header bar, on click this will show the status of the latest transaction (ticket #1326 )

**Designs**

for all the pending transactions that are simple signatures and no token/amount is to be shown, the template from the pending external transaction can be taken ("external" should be replaced with the correct transaction type)

https://app.zeplin.io/project/5a8a92c89c1a166a6a6e8f37/dashboard?seid=5c6c045b4b2e4246346fd549

![image](https://user-images.githubusercontent.com/17235402/53734224-9ef4ec00-3e83-11e9-8d95-6b079d84dff4.png)

**Acceptance criteria**
- [x] There is an ETH symbol representing a given transaction state in the top-right corner 
- [x] Correct transaction type appears in the header
- [x] Pending transaction summary contains: Token name, Amount, Timestamp in UTC
- [x] Tx Hash is a link to the transaction
- [x] for the unsuccessful transaction, "Support Desk" should link to https://support.neufund.org/support/home
- [x] for the successful transaction, there is information about the tab where the changes can be seen (portfolio/wallet) & the button should forward to the tab with changes ("Go to wallet"/ "Go to portfolio")
- [x] for all the pending transactions that are simple signatures and no token/amount is to be shown, the template from the pending external transaction + correct transaction type is shown
- [x] ETH values are always represented with **4 decimals**

**Technical notes**

Further technical background of edge cases #2297

**Testing notes**

- [ ] UI check after dev
