### ISSUE TITLE
Multi-Product / Multi-Jurisdiction Discovery for Investors

### ISSUE THREAD

**Issue by andywalton** [Neufund/platform-frontend#2544]
**Background**
The "Taskforce Legal Product Design" is exploring how we might offer multiple products via multiple different jurisdictions to our customers. This change to the platform has many legal and product considerations.

_For more information please refer to the Epic description: #2546_

---

This ticket is to explore the impact on this direction from the perspective of our **Investors** and how we might design a workable solution.

**Tasks**
1. [x] Explore further solutions to display ETOs from issuers that will be offered via Neufund.org from different jurisdictional and create simple flow diagrams solutions to show how our investors will discover and navigate these offerings via our website and platform.
1. [x] Review for feedback with working group, select solutions to wireframe and prototype further.
1. [x] Wireframe the chosen solution/s and test with developers for technical input. and extended team for further feedback.
1. [x] Review for feedback with working group.
1. [x] Make agreed changes.
1. [x] Write Design and Development tickets for backlog.
1. [x] Share findings with team.
