### ISSUE TITLE
Multi-Product / Multi-Jurisdiction Discovery for Issuers

### ISSUE THREAD

**Issue by andywalton** [Neufund/platform-frontend#2547]
**Background**
The "Taskforce Legal Product Design" is exploring how we might offer multiple products via multiple different jurisdictions to our customers. This change to the platform has many legal and product considerations.

__For more information please refer to the Epic description:__

This ticket is to explore the impact on this direction from the perspective of our **Issuers** and how we might design a workable solution.

**Tasks**
1. [x] Explore further solutions to display ETOs from issuers that will be offered via Neufund.org from different jurisdictional and create simple flow diagrams for each solution.
1. [x] Review for feedback with working group, select solutions to wireframe further.
1. [x] Wireframe the chosen solutions and test with developers for technical input. and extended team Incorporate their feedback.
1. [x] Review for feedback with working group.
1. [x] Make agreed changes.
1. [x] Write Design and Development tickets for backlog.
1. [x] Share findings with team.
