### ISSUE TITLE
Design Issuer ETO form changes as per AGA's matrix and printouts

### ISSUE THREAD

**Issue by andywalton** [Neufund/platform-frontend#2595]
This story will result in design changes to our Issuer setup forms due to the multi-product/jurisdiction ETO offering project we're busy with.

**Please note:** this ticket is for design only so don't try dev against it. It's intended for Kirstyn and it's vagueness is because she knows exactly what to do already.

If you are reading this and you're a developer, please wait, we'll write a ticket/s for development that will explain exactly what changes you need to develop for.

**Key tasks:**
- [x] New Issuer setup form fields have been added to the designs and we have all necessary screens designed.
- [x] These have been checked with AGA.
- [x] Dev tickets have been written.
