### ISSUE TITLE
ETO company detail page changes

### ISSUE THREAD

**Issue by andywalton** [Neufund/platform-frontend#2654]
**Background**
As part of the Neufund multi-jurisdiction ETO products epic we need to make changes to the ETO company pages as new Issuer fields exist. For more information read here #2546 

This ticket is about updating the ETO company page.

---

**Tasks**

### Task 1: Update / edit company page fields

**1. Section LEGAL INFORMATION**

<img width="642" alt="Screenshot 2019-03-29 at 12 39 49" src="https://user-images.githubusercontent.com/609657/55237044-846b2400-5231-11e9-9e77-3d236a8c3018.png">

- [x]  Change label NUMBER OF EMPLOYEES to read TEAM SIZE 

**2. Section ETO INVESTMENT TERMS / EQUITY TOKEN SALE**

<img width="764" alt="Screenshot 2019-03-29 at 12 07 24" src="https://user-images.githubusercontent.com/609657/55237069-90ef7c80-5231-11e9-9497-1f2e50abd125.png">

Add a new few field:
- [x]  ETO jurisdiction (Germany / Lichtenstein) <-- Add at the bottom of the current list

**3. Section ETO INVESTMENT TERMS / TOKEN HOLDER RIGHTS**

<img width="844" alt="Screenshot 2019-03-29 at 12 07 12" src="https://user-images.githubusercontent.com/609657/55237597-d1032f00-5232-11e9-9ece-db3fbbd0341e.png">

- [x] Token tradable (Immediately after ETO / In the future) <-- 3rd item - replaces Token transferability
- [x] Token transferable (Yes / No) <-- 4th item
- [x] Asset type (Security / Investment asset) <-- 5th item
- [x] Dividend rights (Yes -- but it's always yes FYI) <-- 7th item (after Voting rights)

---

### Task 2: Highlight the ETO jurisdiction on the page

Implement as per the screen designs. **@falinebambi please add the designs and a Zeplin link here and a screenshot.**

---

**Acceptance criteria & testing notes**
- [x] ETO company pages include the new fields as described above and in the designs.
- [x] The ETO company pages are linked to from the Dashboard ETOs list. They change the URL as per the pattern above. 
- [ ] The legal jurisdiction disclaimer popup should display in situations as per ticket #2655 
- [ ] The legal jurisdiction of the ETO is highlighted on the page as per the designs.

**Technical notes**
None.

**Comment by falinebambi** [comment]
Zeplin link: https://zpl.io/beDXDAq

**Comment by falinebambi** [comment]
<img width="997" alt="Screenshot 2019-04-08 at 10 43 19" src="https://user-images.githubusercontent.com/17235402/55710649-559c3d00-59eb-11e9-95a7-1e53ba4d2bc4.png">

**Comment by glupiawymowka** [comment]
This is tested on .net, but please mind that as agreed with @andywalton, Task 2 is not done due to lack of designs that were needed for this part. 
I will open a second ticket for this part to not block Task 1 that was done correctly. 

@falinebambi there is also an inconsistency between your designs and the order of ETO investment terms mentioned by Andy, but this is just an FYI as the whole module needs a rebuild according to the guidelines (mind the € signs, big numbers representation, etc.)

**Comment by falinebambi** [comment]
@glupiawymowka this is the new ticket #2759
