### ISSUE TITLE
 [money input] fix dropping special characters if amount is copy-pasted

### ISSUE THREAD

**Issue by glupiawymowka** [Neufund/platform-frontend#2687]
**Description**
We can only enter numbers and "." separator in the money inputs. 
While this is fine for now, as we don't want users to enter abstract contents, this can also lead to some errors. 

If a user copies the amount with a non-accepted special character, it's automatically deleted from the input, sometimes leaving a totally different amount entered. 

**Environment**
all, investment flow, redeem etc 
**Steps To Reproduce** on  .io
1. use any KYC'd fixture to login
2. Start investment 
3. One by one, copy-paste the given amounts and see what happens 
- 100o22.1231236525
- 353,56
- 1021,01

**Actual behavior**
the special character is simply dropped without letting the user know which could lead to incorrect investments 

**Expected behavior**
we need to find a solution, where the user is at least aware that his pasted amount may be different 

- [x] Initial General Component

- [x] Investment

- [ ] Withdraw

- [x] Redeem

- [ ] ETO forms

**Comments, context, logs**

**Screenshots**
pasted the second example : 
![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/93388f35-1ca6-498e-bcb1-c154f06180bc)

**Comment by glupiawymowka** [comment]
- [x] investment - this is correct, we need the same for the other money inputs

**Comment by glupiawymowka** [comment]
- [x] redeem is also done. ETO forms and withdraw left
