### ISSUE TITLE
[ETH WITHDRAW] - general feature redesign and debugging 

### ISSUE THREAD

**Issue by glupiawymowka** [Neufund/platform-frontend#2695]
This is how our Withdraw ETH looks like now. There is a couple of things that are totally wrong, or that could simply be better (probably even more than I mention, so the discovery will probably be needed). 
![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/c9de265f-4e1a-491f-9134-47b64ea87482)

1. We have a simple ETH address format validation. This is cool, but maybe we should also mention somewhere how important it is to triple check the address at this point? 

2. See the given screenshot. You can put as many characters as you want (both with or without separators), but if you put more than 16, the "Withdraw" button simply goes inactive, without any warning, error label, input blockage or so 

3. There is no "Withdraw all" option, like the one we have in the redeem flow

4. We do have some error messages, but these are not really user-friendly 
![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/1bbe1028-2a05-4125-8fd7-f0a57f09d0bd)

5. This is just a simple copy change, but it should be Ethereum address, without the second capital letter 
![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/7522f304-4778-4eda-96b0-5d09a2708eeb)

Feel free to add more ideas and wishes to this ticket

**Comment by rudolfix** [comment]
From my side:
**please redesign** this is really below our standards and looks weird!

**Comment by rudolfix** [comment]
Bump coolness factor! Provide few things for the user that is handling Ether that somehow no one does. Good place is in here!
![image](https://user-images.githubusercontent.com/17202864/55498070-fd5be880-5642-11e9-8c1b-59d7d1c31ab4.png)

1. I should be able to go back and change stuff! (so not only CONFIRM button!)
2. We should provide link to etherscan and see what this address really is.
3. We should check if the address is a smart contract and IMO display proper warning and checkbox "Yes, I want to send Ether to smart contract address"
4. We should check if the address has nonce 0 and display warning "address that you are sending Ether to was never used before!" and also a proper checkbox

In that case we'll avoid many common mistakes users do

I'm bumping this up. Our Ether Withdraw is way below standard

**Comment by falinebambi** [comment]
Talked with @Louisswryan and he will provide a solution

**Comment by Louisswryan** [comment]
Hello,

The new states for this modal are as shown below.

We will be adding new transfer options later and this provides a nice generic platform to deal with all sorts of transactions.

Basically one main state and we do not allow the user to continue into the summary until the transfer details are satisfactory so all error states are contained within this first modal state.

TRANSFER MODAL

Completed: https://app.zeplin.io/project/5a8a92c89c1a166a6a6e8f37/screen/5cbf1a012bdf044be7944613

Empty:
https://app.zeplin.io/project/5a8a92c89c1a166a6a6e8f37/screen/5cbf1a04cba126b7038c668a

Incomplete:
https://app.zeplin.io/project/5a8a92c89c1a166a6a6e8f37/screen/5cbf1a06bfbfebb6d85194e0

Please note - Transfer All will bring the total amount to the user's balance so 'amount of transfer' will equal total minus gas.

ERROR STATES

Address is Smart Contract:
https://app.zeplin.io/project/5a8a92c89c1a166a6a6e8f37/screen/5cbf1a0bbfbfebb6d851958d

Address is First Time Payment:
https://app.zeplin.io/project/5a8a92c89c1a166a6a6e8f37/screen/5cbf1a0e7d01334c0b3e3e6f

Amount Exceeds Balance:
https://app.zeplin.io/project/5a8a92c89c1a166a6a6e8f37/screen/5cbf1a1121e0161fa14e5504

Please note - 'ok' in this instance will fill out the transfer value as if user had clicked 'transfer all' (as described above)

Unrecognised Character:
https://app.zeplin.io/project/5a8a92c89c1a166a6a6e8f37/screen/5cbf1a092bdf044be7944768

TRANSFER SUMMARY

https://app.zeplin.io/project/5a8a92c89c1a166a6a6e8f37/screen/5cbf1ac5e3141d1fc41eb852

TRANSFER PENDING

https://app.zeplin.io/project/5a8a92c89c1a166a6a6e8f37/screen/5cbf1ac5ef626b1fb8c99585

Any questions, please ask :)

**Comment by drakkein** [comment]
Few technical questions: 
* for detection of smart contract address, will the web3's `getCode` solution work? https://ethereum.stackexchange.com/a/28527
* for first time payment detection i bet that `getTransactionCount` is not enough as a solution?

**Comment by Moejoe90** [comment]
For a smart contract. you just need to do 
https://github.com/ethereum/wiki/wiki/JavaScript-API#web3ethgetcode 
If its a smart contract then it should return to you a byte code if its not a smart contract then the specification is not clear so please test it but it will either return `0x` , `null` etc please test this 

In order to figure if the wallet is used or not `getTransactionCount` should be enough as getTransactionCount should return the nonce of a given public key 
if it equals 0 then the wallet is assumed to have bin never used 
why do you think it won't work?

**Comment by drakkein** [comment]
`getTransactionCount` does not include pending transactions, right? So there are cases when wallet will be treated as never used, or I'm just wrong.

**Comment by Moejoe90** [comment]
You can specify 
https://github.com/ethereum/wiki/wiki/JavaScript-API#web3ethdefaultblock parameter in 
https://github.com/ethereum/wiki/wiki/JavaScript-API#web3ethgettransactioncount to "Pending" 
But this will only query our node and the address we are checking is will not use our node. 

I would say  `getTransactionCount` is fine as having a pending transaction a wallet that is used for the first time while you are trying to send a transaction is to is an extreme edge. so no worries from that side

**Comment by glupiawymowka** [comment]
some technical issues to fix now, while Louis is improving the designs. 

**Money formatter**

There is an old formatter used in the ETH withdraw value input. Recently @AlexeyTuboltsev was fixing these all around the platform, so it would be good to use a consistent one here. 

- [ ] please use investment.TSX file or ask Alexey for assistance to change the money formatter to the new one

**Transfer all**
1. Currently, I'm not able to transfer the full amount at all. It used to work when the address was provided before the amount, but I can't reproduce it anymore. The "continue" button is blocked for me unless I manually lower the amount.  After all, we need to handle this situation correctly for all the possible cases:
- [ ] the user copy-pasted the amount, button was not used, address was provided before 
- [ ] the user copy-pasted the amount, button was not used, address was not provided before
- [ ] the user used the "transfer all" button, address was provided before
- [ ] the user used the "transfer all" button, address was not provided before

- [ ] the general expected behavior of this fix is that "The amount exceeds your wallet balance" can be seen only when the amount + gas > total ETH balance

2. Next, when the user uses the button OR copy-pastes the full amount, they should be aware of the fact, that they won't have enough ETH to take any other action on the platform. For now, we solve it as follows: 

- [ ] please put a value "error" message for the case where the user manually or with a button tries to withdraw all ETH from the platform
- [ ] the message copy should be: **COPY FROM @andywalton  NEEDED HERE**
- [ ] the case has to be non-blocking. We want to inform the user, but we can not prevent them from withdrawing if they want, so "continue" button needs to be active (unless data is missing)

**ETH representation on the platform**
According to the new guidelines, we always represent the ETH with 4 decimals. However, if the user enters the amount without decimals, somewhere they will see ".0000", somewhere not, like here : 

![image](https://user-images.githubusercontent.com/18315589/59770183-dc04b300-92a7-11e9-864e-4b7cf2f0b04b.png)

- [ ] please make sure that ETH is always represented with ".0000", even if there are no decimals but zeroes 



*comments, future plans**
What is still to come (in design): 
- new pending state with details (timestamp showing time since the transaction was done etc), but also fitting the new style
- dealing with "transfer all" case that leaves the user without money for GAS, but also not blocking them from emptying their account consciously
- fixing the case where the "transfer to" address is new (currently, this question stays even if the user clicks "OK", we plan to make it a checkbox instead, the same for other similar cases)
- changing the light-gray color to something more visible
- solving the "cut ETH address" issue, probably by showing a nice shorten version + preview button/hover etc

**Comment by Louisswryan** [comment]
Hello @drakkein 

Here is a link to the updated ETH Withdraw designs:

https://app.zeplin.io/project/5d10c5d1bb83d271220e0af7/dashboard?seid=5d36bc4239dcf62f75be21fc

We have new components:

Status Indicators (Status Icons included)
- https://app.zeplin.io/project/5d10c5d1bb83d271220e0af7/styleguide/components?cseid=5d3833e8f58f61632cda10bf

Embedded Alert
- https://zpl.io/V19zQlmhttps://zpl.io/V19zQlm

Please ask with any questions.

Thanks!

**Comment by Louisswryan** [comment]
New design added to account for the Gas<0.0001 scenario:

https://app.zeplin.io/project/5d10c5d1bb83d271220e0af7/screen/5d492b70aa49e44ba8b34645

handed to @drakkein directly

**Comment by glupiawymowka** [comment]
Dear comrades, this was tested on stage. 
Some small fixes still might come in the future, but for now - fingers crossed :D
