### ISSUE TITLE
Issuer ETO forms updates

### ISSUE THREAD

**Issue by andywalton** [Neufund/platform-frontend#2813]
**Background**
This ticket describes a few changes to the Issuer ETO forms. So if you log in as an Issuer the following updates are needed:

**Task 1: Company Information > Company tagline**

The company tagline field needs to be validated to a maximum of 50 characters.

Nice to have would be to add a counter to show how many characters you have left as you type.

![Screenshot 2019-04-28 at 16.21.18.png](https://images.zenhubusercontent.com/5c5861910b133e639c2b7056/b279fd53-0f41-42ba-abc4-ff974ce4cefb)

**Task 2: ETO Terms > Document Language**

If Investment Memorandum → then EN should be selected as the Document Language. It currently shows DE as the language. This should be the case for all ETO types.

This is probably something that should pull through from the backend, in that case let me (@andywalton) know and I'll organise that.

**Task 3: ETO Terms > Additional ETO Terms**

Remove the field titled: PLEASE SPECIFY ADDITIONAL ETO TERMS

![Screenshot 2019-04-28 at 16.35.20.png](https://images.zenhubusercontent.com/5c5861910b133e639c2b7056/60780ffc-1c51-4dcd-9852-7efd6e663af5)

**Designs**
N/A

**Acceptance criteria**
- [x] Company Information > Company tagline allows a max of 50 characters.
- [x] ETO Terms > Document Language for Investment Memorandum defaults to English.
- [x] ETO Terms >Additional ETO Terms field has been removed.

**Technical notes**
None

**Testing notes**
None

**Comment by rudolfix** [comment]
please follow this
https://github.com/Neufund/platform-backend/issues/1656

**Comment by kelexa** [comment]
tested on staging - OK
