### ISSUE TITLE
ETO Form changes to allow Coming soon state

### ISSUE THREAD

**Issue by andywalton** [Neufund/platform-frontend#2885]
### Background

We need to allow our Issuers to list their ETO campaigns earlier, currently our process requires them to have their Investment Terms, Term Sheet & Nominee all setup before we can list them. We want to change this so that we can list them early and say Coming soon and show their public company page with only marketing information completed.

Please refer to the epic Issuer States Update for more detail background: #2879

We therefore need to change a couple of things in our Issuer flow. This ticket describes the changes required:

### Tasks

A company that is listing with only marketing data, can be displayed should be displayed as follows on the investor dashboard:

![Screenshot 2019-05-08 at 15 13 51](https://user-images.githubusercontent.com/609657/57379306-f591e580-71a6-11e9-845a-0f06b0a9f664.png)

Ie. the fields are:

Preview image
Company Name
2 Tags
Founders Quote
“ETO under Liechtenstein jurisdiction” since by default `MINI ETO in LI` is setup in our backend.

To make this possible please do the following:

**Task 1**

<img width="961" alt="Screenshot 2019-05-08 at 15 39 16" src="https://user-images.githubusercontent.com/609657/57379607-84066700-71a7-11e9-919d-c351bb029572.png">

After step 1 (Email verification and KYC), step 2 we only show the fields:

- About
- Legal Info
- Key Individuals
- Pitch
- Media
- Equity Token Info

Therefore:
- [x] Move Equity Token Info from ETO Settings to Company and Marketing Information and;
- [x] Hide the ETO Settings fields.

---

**Task 2**

![image](https://user-images.githubusercontent.com/609657/57379854-fe36eb80-71a7-11e9-9699-ae9011dceadd.png)

- [x] New publish ETO submit box:

> Heading: PUBLISH YOUR ETO
> Text: You have completed all marketing information about your company, by submitting your ETO now you will be able to publish your listing page and start referring your investors to it.  
> CTA: Submit 

---

**Task 3**

![image](https://user-images.githubusercontent.com/609657/57380344-207d3900-71a9-11e9-9dea-9632f921c57b.png)

After approval, the issuer will move into Step 3 that allows them to fill out the `ETO Settings` form fields. Once those are completed the following box will display:

- [x] Revised Submit your proposal submit box:

> Heading: PUBLISH YOUR FUNDRAISING CAMPAIGN
> Text: You have completed all required information about your fundraising, by submitting your ETO now you will be able to publish your investment offer and whitelisting subscription.
> CTA: Submit 

---

### Acceptance criteria
_As described above._

### Technical notes
please read following backend ticket and backend team for api details:
https://github.com/Neufund/platform-backend/issues/1669

 **Task 1**
All forms as specified by Andy must be hidden when state is `preview` and widget described below is **not visible** (widget is visible and ready to submit when marketing data is filled in)

**Task 2**
We have a new widget, we show it when forms that are visible in Task 1 are completed - so it's similar algo to which we use in Submit widget - just only indicated forms participate.
Widget must call `eto_listing_api` (`/etos/me/preview_submission:`) and permission is same as for `submission` method, see swagger.
If method is successfully called `is_marketing_data_visible_in_preview` is set to `visibility_pending` - widget must say that that `YOUR ETO DATA IS REVIEWED` and submit button must be done
widget must go away when we accept in the backoffice app and ``is_marketing_data_visible_in_preview` is set to `visible`

**Task 3**
It's our existing submission widget. no logic changes here. if texting is changed then please do it

### Testing notes
**The default ETO type is by default set to: Mini ETO in LI**

**The document section does not change**
- But if Term Sheet is uploaded in document section before second fundraising submit, it won’t be visible on listing page

**Once an ETO published in `Coming soon` state (ie. with only marketing data):**
- A user sees the rest of the forms: ETO Terms, Investment Terms, Token Holder Voting Rights
- A user is asked to configure all Investment Terms in the forms
- A user is asked to select a Nominee
- A user is asked to upload a signed Term sheet
 
_After this the user submits their ETO for fundraising (second submit button) we need to be able to approve this via our back office, ie. we need a second approve button_

**Comment by glupiawymowka** [comment]
tested on stage
