### ISSUE TITLE
[Nominee account setup 1] - Register / Login views 

### ISSUE THREAD

**Issue by andywalton** [Neufund/platform-frontend#3204]
This ticket is part of the Nominee Dashboard epic #[3203](https://github.com/neufund/platform-frontend/issues/3203).

**TL;DR**

We're building a new dashboard to allow our new user type Nominee to register/login, connect with an Issuer and thereafter to perform tasks required of them before, during and after an Issuers fundraising campaign.

---

**Task**

The focus for this ticket is to create the routing and views that will allow a user to register as a Nominee as well as Login thereafter.

Registration results in a new Nominee user type being added.

We want to provide this registration / login page via a "secret URL", ie. https://platform.neufund.org/nominees/

---

**Designs**
See designs in [Zeplin](https://zpl.io/ameO4vv)

Registration of Nominee
![000a - Register.png](https://images.zenhubusercontent.com/5c5861910b133e639c2b7056/ae4bc1b6-6779-4038-9dcd-d3f23ec10d20)

![000b - Register.png](https://images.zenhubusercontent.com/5c5861910b133e639c2b7056/1e874ca3-b43c-41b2-9966-a53d20ed6ffd)

---
**Tasks**

_Please edit this ticket with relevant tasks to best break up the work._

---

**Acceptance**

- [x] As a new user I can visit a secret URL and register as a Nominee (and create a new Light Wallet)
- [x] Post registration it displays a Nominee dashboard
- [x] I can login as a nominee and view the Nominee dashboard

**Comment by glupiawymowka** [comment]
tested on .io
