### ISSUE TITLE
[Nominee account setup 2] - New account setup wizard

### ISSUE THREAD

**Issue by andywalton** [Neufund/platform-frontend#3205]
This ticket is part of the Nominee Dashboard epic #[3203](https://github.com/neufund/platform-frontend/issues/3203).

**TL;DR**

We're building a new dashboard to allow our new user type Nominee to register/login, connect with an Issuer and thereafter to perform tasks required of them before, during and after an Issuers fundraising campaign.

---

**Task**
Each new Nominee user needs to complete the Neufund account setup before they can link themselves to an Issuer and perform the necessary tasks expected of a Nominee. These setup steps are in order as follows:

1. Verify your email
2. Backup your wallet recovery phrase (Only for Light Wallet)
3. KYC - Verify your company - ie. complete the company KYC and not show the KYC type choice. They shouldn’t be able to select personal KYC in other words. They should follow the Manual process and not have a choice to do video verification please.

Each of the above steps will follow on from the previous step in sequence. Ie. you can’t skip A and go to B or C etc.

Once the Nominee’s account setup is completed we will verify their KYC information as per our current setup and provide a message to say that their account verification is being processed and that we’ll get back to them within 1-2 working days.

1. On Success we highlight this success via an alert and show next steps - Nominee setup..
2. On Failure, our customer care agents will contact the Nominee directly to manage the processing of their KYC inorder to verify them.
3. While they wait for a/b above, the Dashboard should show that there are No Actions Required

---

**Designs**
See designs in [Zeplin](https://zpl.io/ameO4vv)

See sections:
1. Account setup #1 (Verify email)
2. Account setup #2 (Backup recovery codes)
3. Account setup #3 (Company KYC)

![001a - Account setup - Verify Email](https://user-images.githubusercontent.com/609657/61288866-54d42d80-a7c8-11e9-9694-ff8419560d84.png)

![002a - Account setup - Backup recovery phrase](https://user-images.githubusercontent.com/609657/61288875-5aca0e80-a7c8-11e9-9fb8-494bb752f845.png)

![003a - Account setup - KYC company](https://user-images.githubusercontent.com/609657/61288884-5e5d9580-a7c8-11e9-825f-f549b410b932.png)

![004 - Account setup pending verification + empty state](https://user-images.githubusercontent.com/609657/61288888-60bfef80-a7c8-11e9-9cdf-0ce00b6ebd11.png)

---
**Tasks**

_Please edit this ticket with relevant tasks to best break up the work._

---

**Acceptance**
- [x] A Nominee is guided through the 3 steps mentioned above.
- [x] Step 2 - backup your recovery phrase kicks off our existing recovery phrase steps - on completion it lands you back on the dashboard but it's moved you to the next step.
- [x] Step 3 - starting KYC will open our existing KYC flow but fast forward to the company step. On completion it lands you back on the Dashboard and shows you the success message and that we will get back to you within 1 - 2 working days.

**Comment by glupiawymowka** [comment]
![image](https://user-images.githubusercontent.com/18315589/61878195-d3c81500-aef0-11e9-8d16-4e29dd4c02ce.png)
is this a question or an order? xD

**Comment by AlexeyTuboltsev** [comment]
> is this a question or an order? xD

a question. I use `!` for orders

that\s how it looks like in zeplin, see here:
https://app.zeplin.io/project/5d2b7e0bd1281e565d9d08e4/screen/5d2c4c0269a8664c70c83e35
