### ISSUE TITLE
[Nominee task 1 of 4] - Agree and sign ETO Token Holder Agreement

### ISSUE THREAD

**Issue by andywalton** [Neufund/platform-frontend#3270]
This ticket is part of the Nominee Dashboard epic #[3203](https://github.com/neufund/platform-frontend/issues/3203).

**TL;DR**

We're building a new dashboard to allow our new user type Nominee to register/login, connect with an Issuer and thereafter to perform tasks required of them before, during and after an Issuers fundraising campaign.

A nominee currently has to perform 4 tasks for an Issuer:

1. Agree and sign the ETO's Token Holder Agreement
2. Redeem ETO share capital to their linked bank account
3. Confirmation that Nominee has wire transferred the share capital to the Issuers bank account
4. Upload and sign the Investor Shareholder Agreement they signed (ie. at a notary)

---

**Task**
This ticket is to do with the task that the Nominee agrees and signs the ETO Token Holder Agreement.

These steps are as follows:

1. The Dashboard will highlight the action that the Nominee needs to agree and sign the Token Holder Agreement (THA) - a call to action will...
2. Open a modal that allows the Nominee to download the THA to read this document
3. They need to check a checkbox stating that they have read and agree to the THA
4. Doing so will enable the modal button Sign to sign this document, clicking Sign will open our signer
5. In the case of the Nominee using a Light Wallet (LW) they will be asked to enter the LW password. Similarly, if they are using a Ledger they will need to sign using their Ledger.
6. On successfully signing, they will see a success message in the modal and they can close this to go back to the Dashboard. Signing should follow our current validation we're using for this and behave the same as this current module.

If there are no actions to perform, they will see a No Actions Required message on the Dashboard.

Should we be able to show the recent activity, the THA being signed will be highlighted in the activity feed on the Dashboard.

---

**Designs**
See designs in [Zeplin](https://zpl.io/ameO4vv)

Scroll down to section: **5) Nominee task #1 - Sign THA**

---
**Tasks**

_Please edit this ticket with relevant tasks to best break up the work._

---

**Acceptance**
- [ ] A Nominee is told they should sign the THA.
- [ ] They can download and view the THA, accept they have read and agree to the THA which will disable the Sign CTA button.
- [ ] Clicking Sign triggers our current signer. On successfully signing we highlight this to the Nominee.
- [ ] On success we move the Nominee to the next step (or highlight that they're isn't anything for them to do yet)

**Comment by andywalton** [comment]
Doh, this is a duplicate. This ticket already exists. Closing it.
