### ISSUE TITLE
[Nominee setup 2] Link Nominee bank account

### ISSUE THREAD

**Issue by andywalton** [Neufund/platform-frontend#3271]
This ticket is part of the Nominee Dashboard epic #[3203](https://github.com/neufund/platform-frontend/issues/3203).

**TL;DR**

We're building a new dashboard to allow our new user type Nominee to register/login, connect with an Issuer and thereafter to perform tasks required of them before, during and after an Issuers fundraising campaign.

As part of the Nominee setup they are required to link their bank account as they will need to redeem share capital should their Issuers ETO be successful.

---

**Task**
This ticket is to do with getting the Nominee to link and verify their bank account.

These steps are as follows:

1. The Dashboard will highlight that the Nominee should link and verify their bank account with a call to action to prompt this.
2. Click this will start our usual link bank account flow and tell the Nominee how to do so.

After completing the linked bank account steps, we should highlight that their is nothing for the Nominee to do in the Dashboard if this is the case.

__If possible, if we can show the recent activity a Nominee has completed, on successfully linking their bank account we should highlight this in the activity feed on the Dashboard.__

---

**Designs**
See designs in [Zeplin](https://zpl.io/ameO4vv)

Scroll down to section: **4) Link Nominee bank account**

---
**Tasks**

_Please edit this ticket with relevant tasks to best break up the work._

---

**Acceptance**
- [x] A Nominee is told they should link and verify their bank account on the Dashboard.
- [x] The link flow works as per our current implementation
- [x] On success we move the Nominee to the next step (or highlight that they're isn't anything for them to do yet)
