### ISSUE TITLE
[WHITELISTING] - fixes to the current flow 

### ISSUE THREAD

**Issue by glupiawymowka** [Neufund/platform-frontend#3382]
**Description**
The whitelisting needs a total re-design, but we could fix some problems before we get there. 

**Tasks**

1.  We're validating the min whitelist commitment, but not the max one 
![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/23007195-0014-4ed3-80bf-11bc3286c4d0)

status: 400
title: "Pledge with amount 50000000 is not within bounds of 100000 and 15920398.00995024876000 for eto id 0x2e2eb728c6974C93a564Fe615847573603ADDaDa"
type: "exceptions.PledgeNotWithinBoundsException"

ACCEPTANCE CRITERIA:
- [ ] the similar information as for the min amount shows up, instead of the unclear error bar 
![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/f6b43828-5e9b-45e7-8262-935d5227bf10)

2. See the screen above. We should not add .00 to full numbers, so in this case we just show 100 000
ACCEPTANCE CRITERIA:
- [ ] Full number is not represented with non existing decimals 

3. Widget size changes once the user starts typing 
![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/cca76853-d223-42da-9f33-79562a03b310)

4. There's a place to show commited amount in the incoming email, but nothing was added there. 
If this is too much work, please let @vizmab know so she deletes this part from the email 
![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/f657aa58-bc07-4937-aec9-ad95edd43bd9)

ACCEPTANCE CRITERIA: 
- [ ] `Amount commited` either show the valid amount, or is deleted completely 

5. User should not be able to enter dot `.` in the input field. `1000.` is possible to enter. only round numbers, guys, without decimals!
- [ ] only digits accepted in input

**Comment by rudolfix** [comment]
Technical information

ad. 1 backend will provide `effective_max_ticket` value against which you should validate maximum value
ad 2. this applies only to `amount` not prices or rates, I really hope you've made this difference in your formatters. all amounts that are round (without decimal places) are displayed without decimal dot

**Comment by andywalton** [comment]
Hello, so I have some initial ideas about improving the UX. This needs more ideation and design but in the meantime some of the validation - ie. min commitment size => min ticket size etc. could commence.

For the ongoing UX see here: https://whimsical.com/EUHDm1RM1MQejf5MGqu84j

**Comment by glupiawymowka** [comment]
tested on stage & released
