### ISSUE TITLE
[Company page] - hide ISHA from non-KYC'd users

### ISSUE THREAD

**Issue by andywalton** [Neufund/platform-frontend#3586]
### Background
This ticket describes changes the conditions for when we can display the Investment and Shareholder Agreement (ISHA) and Signed Investment and Shareholders Agreement (Signed ISHA) to users. 

### Tasks
We need to make the following two changes on the issuer company page:

**1) Hide these ISHA documents from non-KYC’d users** 

Do this in two places on the company detail page:

- [x] 1.1) In the section `ETO INVESTMENT TERMS`, show the Investment and Shareholder Agreement only to users who are KYC.

<img width="409" alt="Screenshot 2019-10-08 21 16 49" src="https://user-images.githubusercontent.com/609657/66398345-93206800-ea18-11e9-8bd3-2b9470be67ac.png">

- [x] 1.2) In the section `LEGAL DOCUMENTS`, show the Investment and Shareholder Agreement only to users who are KYC.

<img width="414" alt="Screenshot 2019-10-08 21 36 12" src="https://user-images.githubusercontent.com/609657/66398366-9ae00c80-ea18-11e9-93fe-3d6a253e9b23.png">

**2) Add a new conditional modal to display a document confidentiality agreement**

- [ ] 2.1) When a KYC’d users clicks to download an ISHA document, we will introduce a new Confidentiality modal. The user then needs to agree to this confidentiality agreement before being able to download and view the ISHA.

 This modal should only be displayed based on a constant that will check against an array of Issuer company IDs, if the company requires this confidentiality agreement to be shown, we then will display the modal. In other words, not all companies will need this.

Please use the same Terms of Use modal as below with the following copy and behaviour:

<img width="801" alt="Screenshot 2019-10-08 21 48 05" src="https://user-images.githubusercontent.com/609657/66398393-a3d0de00-ea18-11e9-8f8d-17b3693a93c0.png">

- [ ] 2.2) Image: Please use the same image as our Terms of Use

- [x] 2.3) Heading: Please read this documents terms

- [x] 2.4) Body: By accessing this confidential document, the Neufund platform qualified investor, having full understanding of the consequences, undertakes an obligation to the Company and to each of the current shareholders of `<company_name>`. that it shall not use any of the information contained in this document for any purpose other than evaluation of its/his/her investment in offered by this offering. The liability of such qualified investor to each of the named parties to Investment and Shareholder Agreement (ISHA) for breach of the confidentiality provisions shall to the maximum extent permitted by law.

- [x] 2.5) CTA left: I don’t agree
- [x] 2.6) CTA right: I agree

- [x] 2.7) If a user clicks `I don’t agree`, the modal closes
- [x] 2.8) If a user clicks `I agree`, the ISHA document is downloaded, the modal closes, and we store on `local storage` that the user has agreed to this document’s terms.

### Designs
Please use existing components. This would mostly be logic work.

### Technical notes

- We don’t require any backend for this.
- We need to store a list of variables for the company that use this and conditional display the modal only to those company_id’s that are on that array. @pstroinski will provide a list of `company_id`'s for the constant.
- We need to store the user answer for the confidentiality agreement in local storage and don't show again if the user accepted.

**Comment by glupiawymowka** [comment]
tested on stage
