### ISSUE TITLE
[Company page] Add fundraising statistic tab

### ISSUE THREAD

**Issue by andywalton** [Neufund/platform-frontend#3589]
### Description

On the company page, the aim is to repurpose our ICO Monitor app and strip down the [fundraising detail views](https://icomonitor.io/#/0x01A1f17808edAE0B004A4F11a03620D3d804b997) so that we can display these statistics inside an iFrame in a new tab for each issuer.

### Tasks

We need to make the following changes:

- [ ] 1) Add a new tab section to the issuer company pages that allow you to tab between `Campaign Overview` and `Fundraising Statistics`

- [ ] 2) Fundraising Statistics tab is visible: (a) always when ETO on chain state is PUBLIC including non logged user (b) only when investor is eligible for whitelist - on chain state is WHITELITING
it's exactly the same logic we use to show PRE SALE countdown vs. pubic countdown

- [ ] 3) In the stripped down ICO Monitor views should match the styling of the platform as close as possible (see Designs below) and this page should be embedded inside an iFrame for now.

- [ ] 4) Update the styling of the ICO Monitor as close to the **Designs**. Two things:
- [ ] 4.1) Match the width of the`.container` to 1140px on desktop, which is the same as the max-width of our company page
- [ ] 4.2) Change the bar graph fills from purple to `#C6D30D` - Neufund Dark Neon
- [ ] 4.3) Change all words that say ICO to `offering`.

 ### Designs

Designs are in Zeplin: https://zpl.io/aRXvD8e

_Notes:_

- You can inspect the code for the tabs only, the rest of the page was patched together using screenshots so it’s static.
- Please take note of the notes in Zeplin on each page.
- See this file: [icon-monitors-css.txt](https://github.com/Neufund/platform-frontend/files/3702758/icon-monitors-css.txt) with recommend CSS changes that I made to hack the styling of the ICO Monitor in the browser to be similar to the platform.

### Technical details
A few preparations in ICO monitor were already done
- there's a special route to just the stats components:
`https://icomonitor.io/#/stats/{eto_id}`
- task 4.3 is already done for the component displayed in the iframe
- please hardcode following link for `stage` and `io` for the iframe
`https://test.icomonitor.io/#/stats/0x01A1f17808edAE0B004A4F11a03620D3d804b997`

Please complete platform part before amending icomonitor code. Preferably we have working commit deployment on codechecks, we check it out and then we improve ico monitor.

however if you want to run it locally you need to configure it. here's how you do it. also please note that icomonitor code is BAD and I think there's not much point to fix it... at least now.

1. create following `env.json` in repo after clone
```
{
  "rpcHost" : "https://icomonitor.io/nodes/mainnet",
  "GaTrackingId" : "",
  "fbPixelId": "000000000"
}
```
2. Install mod header in chrome
3. set following headers
```
{"title":"ICOMONITOR","hideComment":true,"headers":[{"enabled":true,"name":"Origin","value":"icomonitor.io","comment":""}],"respHeaders":[{"enabled":true,"name":"Access-Control-Allow-Origin","value":"https://localhost:3000","comment":""},{"enabled":true,"name":"Access-Control-Allow-Credentials","value":"true","comment":""},{"enabled":true,"name":"Access-Control-Allow-Headers","value":"Content-Type","comment":""}],"filters":[],"appendMode":""}
```

you can import the above into mod header

4. yarn run serve

### Testing
As per the tasks.

Thanks!

**Comment by rudolfix** [comment]
ad (2) please always show the button for the issuer (pre-sale and sale) so when issuer sees the profile in his own context (`/etos/me`)
