### ISSUE TITLE
Investment flow - invest step 1 quick fixes

### ISSUE THREAD

**Issue by andywalton** [Neufund/platform-frontend#3593]
### Background
Minor improvements to the investment modal step 1.

### Tasks
**1. Lets make it more clear that the what the ticket price is, and if it includes a discount, that we highlight that**

So, before the change we have this:

![platform neufund io_eto_view_DE_abf7e218-1a21-4423-a600-20504e40f3c2 (2)](https://user-images.githubusercontent.com/609657/66472716-ccb0ac00-eac8-11e9-90a0-90527290a67d.png)

After the change we have this:

![Invest with ETH changes to show token price + discount more clearly](https://user-images.githubusercontent.com/609657/66472740-d76b4100-eac8-11e9-90ac-859e9f7bb250.png)

Note this has some styling changes (mainly font sizing, positioning and some colours) - I will send you a separate hacked HTML file @desfero.

*Copy changes:*

Wallet selector changes to:
- [x] `Which balance would you like to invest from?`

Investment amount changes to:
- [x] `How much would you like to invest?`

The paragraph above the amount input field should read:
- [x] `You'll invest at a token price of xxx EUR which includes a x% discount.`

If no discount exists. The sentence should read:
- [x] `You'll invest at a token price of xxx EUR.`

Note both the token price and discount should be dynamic.

**2. Fix below token price unclear error message**

@desfero picked up this bug that we aren't highlighting clearly the token price correctly during the investment flow - it doesn't make sense particularly for ETH investment.

Screenshot showing the issue:
![image](https://user-images.githubusercontent.com/609657/66472486-4b591980-eac8-11e9-84e7-b1b94f800215.png)

A questions you might ask looking at that issue: Is that the ETH price or EUR. It's actually EUR?

- [x] Please update the error message firstly to be:
1. for ETH investing
`The amount is below the minimum ticket size of 100 000 EUR ≈ 607.1084 ETH`

2. for nEUR investing
`The amount is below the minimum ticket size of 100 000 EUR`

After this change it should look as follows:

![Invest with ETH changes to show token price + discount more clearly--with eth below ticket size error](https://user-images.githubusercontent.com/609657/66472839-0aadd000-eac9-11e9-859f-b56b500ec61b.png)

**3. Add some EUR conversion for ETH**

In two places:

- [x] 1. Amount input field
<img width="564" alt="Screenshot 2019-10-09 19 21 11" src="https://user-images.githubusercontent.com/609657/66473451-3f6e5700-eaca-11e9-852f-6472ddddb3f1.png">

- [x] 2. For the Total and Gas for ETH (sorry add 
<img width="316" alt="Screenshot 2019-10-09 19 21 05" src="https://user-images.githubusercontent.com/609657/66473459-439a7480-eaca-11e9-89d2-f4544a54f8a1.png">

**Technical notes**
None

**Testing notes**
Same as tasks

**Comment by pstroinski** [comment]
@desfero of course the discount price for the user added to the whitelist should be shown only to the whitelisted user with the proper % (as there might be different % per whitelisted user).

**Comment by rudolfix** [comment]
Displaying prices and discounts requires accessing ETOTerms smart contract. Access ETOTerms contract via ETOCommitment::etoTerms()

1, calculating token prices properly
- public sale price: call ETOTerms::calculatePriceFraction(Q18 - ETOTerms::PUBLIC_DISCOUNT_FRAC()) 
- pre-sale price: call ETOTerms::calculatePriceFraction(Q18 - ETOTerms::WHITELIST_DISCOUNT_FRAC()) 

2. There are two types of discount
- personal discounts that are given up to a certain amount and with particular discount
- pre-sale discount

we need to display information on both

3. displaying personal discounts (can be fully skipped in public sale)
query for the whitelist ticket for an investor:
```
ticket = await etoTerms.whitelistTicket(investor);
```
function whitelistTicket(address investor)
        public
        constant
        returns (bool isWhitelisted, uint256 discountAmountEurUlps, uint256 fullTokenPriceFrac)
```
compute personal discount amount: subtract already invested amount (IInvestorTicket.equivEurUlps - you have this in state already) from discountAmountEurUlps 
if  > 0 then there's a personal discount available with amount above and discount 18 - fullTokenPriceFrac

you can obtain token price for personal discount by calling ETOTerms::calculatePriceFraction(fullTokenPriceFrac)

The sentence you should formulate should be:
Up to {discount amount} EUR, you'll invest at a token price of {personal price} EUR which includes a {personal discount}% discount. Above that amount you'll invest at a token price of {whitelist price} EUR which includes a {whitelist discount}% discount.
