### ISSUE TITLE
[ETO Countdown] Small layout change

### ISSUE THREAD

**Issue by andywalton** [Neufund/platform-frontend#3667]
**Task**
This is a small change to improve the ETO Countdown component which currently has a layout like this:

<img width="255" alt="Screenshot 2019-10-24 09 21 41" src="https://user-images.githubusercontent.com/609657/67462443-d812e400-f63f-11e9-977c-64c36f4ee52c.png">

Please change it to look like this:
<img width="393" alt="Screenshot 2019-10-24 09 28 31" src="https://user-images.githubusercontent.com/609657/67462904-b49c6900-f640-11e9-9b5b-dade361c99f3.png">

The changes are as follows:
- [x] Move the date and day below the 4 counter boxes
- [ ] Reformat the date and day text to be `Monday, 28 Oct 2019 at 12:12:12 UTC` and sentence case the text, it's currently uppercase.
- [x] Refine the margin between the date and day text and the counter - make the top marging equal `margin-top: 0.5rem;`, which is 8 pixels. This way we'll have spacing consistency.
