### ISSUE TITLE
Presale soft cap changes

### ISSUE THREAD

**Issue by andywalton** [Neufund/platform-frontend#3679]
### Background
This is related to the #3662 Soft Cap epic, specifically changes needed for ETOs that are busy with their Presale.

This ticket deals with showing changes to the ETO preview cards and the company listing page and what investors will see based on if they are on the whitelist and logged in and those who aren't logged in and or not on the whitelist.

### Designs
See designs in Zeplin here: [https://zpl.io/V495jPz](https://zpl.io/V495jPz)

Look under the section `Presale soft cap states`

<img width="760" alt="Screenshot 2019-10-28 10 59 17" src="https://user-images.githubusercontent.com/609657/67669402-16770e80-f972-11e9-9fdf-d5e770c98c9c.png">

### Tasks
Please review each image in Zeplin and note the annotation for a detailed breakdown of the tasks. 

Here's a simple list of tasks:

- [x] **007a - Presale ETO card - soft cap reached - show this for people who aren't logged into the platform**

- [x] **007b - Presale ETO card - soft cap reached - show this for people who are logged in and on the whitelist**

- [x] **008a - Presale company page - soft cap reached - show this for people who aren't logged into the platform**

- [x] **008b - Presale ETO card - soft cap reached - show this for people who are logged in and on the whitelist**

### Acceptance criteria
As per the Tasks.

### Technical notes
N/a

### Testing notes
As per the Tasks and Zeplin annotations.
