### ISSUE TITLE
implement wallet connect web3 wallet

### ISSUE THREAD

**Issue by rudolfix** [Neufund/platform-frontend#4060]
**Background**
Implement a fourth type of wallet that will inject a web3 handling linking external wallets via wallet connect. You may start with reference implementation. You will however need to extend it and possibly fix various shortcomings so feel free to fork it. In theory it should be drop-in replacement for any injected browser wallet.

In hidden route you should be able to display QR code and initalize a pub sub via `wc_bridge_api` component already exposed on `dev`.

You should be able to use QR code to connect to mobile metamask wallet.
You should present message and transaction signers

Provide feature flag to disable wallet connect on production.

**Designs**
Please start from metamask login template but display QR code instead. Ignore registration route. You may reuse metamask signers but maybe at least put some different icon :)
You may ask @andywalton for help with some wireframes.

**Acceptance criteria**
* [x] add a new wallet type according to the design pattern (wallet + connector)
* [x] launch login process via hidden route, ignore registration
* [x] use reference wallet connect web3 implementation
* [x] we must restrict commands sent to connected wc-wallet. in fact the only commands we may send are those that require access to private key: `eth_sign`, `eth_signTypedData`, `eth_sendTransaction` and `eth_sendTypedTransaction`. all the other JSON RPC commands must be routed to the transactional or other nodes.
* [x] we must assume that mobile app does not listen to our messages on web sockets and we'll not receive response quickly and messages may expire.
* [x] this means that we need to implement timeouts for the login via QR code and on the signers. it would be good to show the countdowns if only just for reference. see tech details.
* [x] if there's an timeout on QR code read we should replace it with a new one/hide it/blur it. the timeout shall be long (like 10 minutes)
* [x] when session is disconnected by the remote wallet you log out immediately.
* [x] if you logout due to inactivity or for any other reason you must disconnect session gracefully (it seems this is `wc_sessionUpgrade` with all parameters being null)
* [x] test case when browser tab is closed and reopened. you may store session information in local storage... but there's symmetric key so let's talk.
* [x]  we should use `clientMeta` from `wc_sessionRequest` response to identify wallet subtype, in particular Neufund app. For each known wallet subtype we should be able to configure how it behaves. see tech details
* [x] if update session happens that changes accounts - handle like we handle metamask changing addresses

**Technical notes**
*defining wallet subtypes*
Let's do it correctly: based on client meta we assign a features matrix to the connected client that should include
* wallet subtype (default: UNKNOWN)
* sign transaction JSON RPC command (default: `eth_sendTransaction`)
* sign message (default: `eth_sign`)
* session timeout (default: 10 minutes)
* sign timeout (default: 2 minutes) 

FYI: metamask uses `eth_signTypedData` as message signer.

additional flags for Neufund app extensions
* supports explicit timeouts
* supports session pings
* supports remote kyc
* supports light wallet migration

Ideally you could apply same mechanism to web3 wallets where we have a mess of ifs!

**Future Extensions**
We must support any compatible wallet, there are however a few specials for Neufund app.
* [ ] you can suggest message timeout when sending JSON RPC command
* [ ] we must send additional `wc_sessionPing` message to keep session alive - for example each minute - if there was no communication from any end (do not overwrite existing messages)
* [ ] import lightwallet procedure will be done as session connect where `salt` is passed in the request
* [ ] new wc_session command to launch onfido/id now SDK on the mobile from the desktop

**Testing notes**
You must be able to log in and see your wallet balances using Metamask mobile attached to dev network

**Comment by Aimeelu668** [comment]
楼主大大总结的很到位！不过自己开发的钱包都是热钱包机制，节点同步慢，归集非常麻烦，最重要的是这些私钥存在服务器上很危险，天天被黑客盯着。当时我们平台有50多万会员，为了解决钱包问题折腾了一年，最终放弃了，选择了优盾钱包（ https://www.uduncloud.com）
。通过API直接接入就行，有独立客户端操作审核、归集等，私钥也是自己在客户端上管理，服务器上不存。用了快一年，没有出现安全问题，财务都反馈说体验很好。我们也终于可以专注于业务开发了。推荐试试

**Comment by Aimeelu668** [comment]
楼主大大总结的很到位！不过自己开发的钱包都是热钱包机制，节点同步慢，归集非常麻烦，最重要的是这些私钥存在服务器上很危险，天天被黑客盯着。当时我们平台有50多万会员，为了解决钱包问题折腾了一年，最终放弃了，选择了优盾钱包（ https://www.uduncloud.com）
。通过API直接接入就行，有独立客户端操作审核、归集等，私钥也是自己在客户端上管理，服务器上不存。用了快一年，没有出现安全问题，财务都反馈说体验很好。我们也终于可以专注于业务开发了。推荐试试
