### ISSUE TITLE
Mobile App Security Checklist

### ISSUE THREAD

**Issue by rudolfix** [Neufund/platform-frontend#4150]
**Background**
We add various security requirements here to make sure we have them all implemented before app store release

**Common Requirements**
* [ ] **Never use external storage like memory cards for anything**. No app installs, no reading or writing data. No importing of wallets from files.
* [ ] **We must require valid Neufund issued certificate when connecting to backend and bridge server**. We’ll hardcode fingerprint and refuse to call anthing that does not conform. When our backend certificate is changed we must release new version of the app. We should have overlapping certificates and allow previous and next fingerprint (normal replacement) or just new (old certificate revoked).
* [ ] **We need Cloudflare DDOS protection working**. That means solving javascript challenge and passing resulting cookie to all backend api requests (yes you may get javascript challenge instead of json and we need to handle it)
* [ ] **If any sensitive information is shown like recovery codes, making screenshots must be disabled**
* [ ] **Secure random number generator must be used**

**iOS Requirements**

**Android Requirements**
* [ ] Installing app on external storage is banned!
* [ ] Android 9 is a minimum due to new process isolation
