### ISSUE TITLE
Mobile App MVP designs

### ISSUE THREAD

**Issue by Trilbi** [Neufund/platform-frontend#4170]
**Designs**
- Screen designs in Zeplin: zpl://project?pid=5e6f48a43076c61012fd3793 / https://zpl.io/anR1n3r
- Since the flow of screens is not always clear in Zeplin, it can be viewed in Figma (let me know if you need access to the project): https://www.figma.com/file/orm5HmF3SJoon4HuCT6VoU/%F0%9F%93%B1-Mobile-App?node-id=1316%3A9804
- There are separate tickets (below) for components that need to be created for these UI designs

**Acceptance criteria**
- [ ] Works on Android (OS version 9+)
- [ ] Works on iOS (OS version ...)

**User Flows:**
- [ ] User can restore a wallet with Recovery phrase and/or Private Key #4231
- [ ] User can Sign up to Neufund on the mobile app #4219 
- [ ] User can Log in to / Unlock existing Neufund app (has already signed up or restored a wallet) #4226 
- [ ] User can scan a QR code (and enable camera permissions) #4250
- [ ] User can sign a transaction #4288
- [ ] User can see Recovery Phrase and/or Private Key on Profile #4249
- [ ] User can enable Push Notifications (ask when user lands on Home view the first time after sign up #4219 and #4249 (Profile ticket)) (for internal use for MVP - the next phase will include a "permissions primer" for real users to enable push notifications in a user-friendly way)
- [ ] User can "Switch account" - see profile ticket #4249

**Screens:**
- [ ] App loading state #4224 
- [ ] Sign up landing screen #4219
- [ ] Log in landing screen #4226 
- [ ] Home/Dashboard shows a list of Assets (maximum 3), Wallets (maximum 3) and Investments #4242
- [ ] Home/Dashboard - Action: Scan QR code #4250
- [ ] Loading state for Home/Dashboard #4242 
- [ ] Portfolio shows full list of assets #4247 
- [ ] Wallet shows full list of wallets and transactions #4248 
- [ ] Loading state for Portfolio and Wallet (See Portfolio/Wallet tickets)
- [ ] Profile #4249
- [ ] Profile - Action: Copy wallet address
- [ ] Profile > Recovery Phrase and/or Private key
- [ ] Profile > Active session
- [ ] Profile > Switch/toggle for Push notifications 
- [ ] Profile > Switch Account
- [ ] Modal for signing transactions (For MVP this will be a centred modal as per Pawel's comments and for low priority or the next phase would ideally be an action sheet / a bottom sheet style would be used)

**Components:**
- [ ] Buttons #4172 
- [ ] Textfields #4199 
- [ ] List items (Assets, Transactions, Profile) #4201 
- [ ] Modals/Dialogs #4288 
- [ ] Nav bars i.e. headers #4205  
- [ ] Tab bar 
- [ ] Top bar

Link to all components: https://zpl.io/an43q9O

**Technical notes**

**Testing notes**
(Need input from QA please)
- Download TestFlight app

**Comment by desfero** [comment]
Confirmed with @andywalton , this one is no longer needed
