### ISSUE TITLE
[Wallet Connect] Page improvements

### ISSUE THREAD

**Issue by andywalton** [Neufund/platform-frontend#4410]
**Description** 
This ticket improves the current WalletConnect page on the platform by adding more content to the page and changing the experience slightly to make it more usable.   

The current user flow:  
1. As a user I can navigate to our WalletConnect page.
2. This currently displays the WalletConnect modal automatically - which is good because you can simply scan the QR code and connect to the platform but bad because it's a modal automatically opening and the page behind it, you're unsure what content it's displaying.
3. If you close this modal, we show a page with very little information and an error. The user also sees this for the first time.

This ticket will focus on improving point 3. and making a change to point 2.

**Designs**
![Screenshot 2020-06-10 10.19.13.png](https://images.zenhubusercontent.com/5c5861910b133e639c2b7056/1359ad00-a08f-4a05-99ba-329477523f73)

You can view the screen designs in Zeplin here: https://zpl.io/angAmrv

See the designs for the relevant icon and components used (which should link through to the design system in Zeplin also).

**Tasks**
Please implement the following changes to the WalletConnect user flow:

- [x] As a user I can navigate to our WalletConnect page but the WalletConnect modal doesn't display immediately.

- [x] Instead, I now see a page that displays a little more information about connecting to Neufund using WalletConnect. The `Learn more` should open a link in a new tab to `https://walletconnect.org/`. 

The primary call to action `Connect using WalletConnect` should open the WalletConnect QR code modal we've already implimented.

- [x] The user can then scan a QR code using a WalletConnect compatible wallet to access the platform. If this modal is closed or there is an error, a user will then see the WalletConnect landing page but it with an error showing that asks them to retry as there was an issue connecting to their wallet.

- [x] While this feature is in beta, please link the `Customer Care` link to `https://support.neufund.org/support/tickets/new`

- [x] Take note of the responsive changes for our smallest mobile breakpoint (screens <=540px wide I think). See the mobile screen designs.

- [x] The header navbar should show both our `Log in` and `Get started` buttons.

**Technical requirements**
There are no technical changes other initiating the WalletConnect modal only on pressing the CTA visible on at the WalletConnect URL.

**Acceptance**
@glupiawymowka , as per the tasks.
